### ISSUE TITLE
天涯的抓取,总是提示"请检查链接是否正确，或者不支持抓起该网页"

### ISSUE THREAD

**Issue by xiaoxuz** [Nyloner/Nyspider#2]
天涯的抓取,总是提示"请检查链接是否正确，或者不支持抓起该网页"

异常信息是Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

什么原因？

**Comment by Nyloner** [comment]
需要安装lxml。
`pip install lxml`
