### ISSUE TITLE
大众点评-评论

### ISSUE THREAD

**Issue by stutys** [Nyloner/Nyspider#5]
你好~感谢您的分享~
准备用您的大众点评的代码，爬取一下他们的用户评论数据~
但是不太明白您的代码结构？（新进的爬虫小白，Thanks♪(･ω･)ﾉ）

**Comment by Nyloner** [comment]
dianping目录下没有爬取评论的代码，建议自己写一下或者找找其他代码吧

**Comment by stutys** [comment]
OK~好的，谢谢~
